import { Injectable, Logger } from "@nestjs/common";
import { EntityManager } from "@mikro-orm/postgresql";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { Domain } from "./entities/domain.entity";
import { env } from "../shared/config/env";

@Injectable()
export class TraefikSyncService {
  private readonly logger = new Logger(TraefikSyncService.name);

  constructor(private readonly em: EntityManager) {}

  async sync() {
    const domains = await this.em.find(Domain, { verifiedAt: { $ne: null }, isDeleted: false }, { populate: ["tenant"] });
    const custom = domains.filter((d) => !d.domain.endsWith(env.PLATFORM_HOST) && d.domain !== env.PLATFORM_HOST);
    const routers = custom
      .map((d, i) => {
        const name = `wufud-custom-${i}`;
        return `    ${name}:
      rule: Host(\`${d.domain}\`)
      entryPoints:
        - websecure
      service: wufud-frontend@docker
      tls:
        certResolver: customdomains
      priority: 80`;
      })
      .join("\n");
    const yaml = `# AUTO-GENERATED by Wufud TraefikSyncService — do not edit.
http:
  routers:
${routers || "    wufud-custom-placeholder:\n      rule: Host(`wufud-none.invalid`)\n      service: noop@internal\n      priority: 1"}
`;
    try {
      mkdirSync(dirname(env.TRAEFIK_DYNAMIC_PATH), { recursive: true });
      writeFileSync(env.TRAEFIK_DYNAMIC_PATH, yaml);
    } catch (err) {
      this.logger.warn(`Traefik sync skipped: ${(err as Error).message}`);
    }
  }
}
