import Link from "next/link";
import type { PublicHostContext } from "@wufud/contracts";
import { ArrowRight, CalendarDays, Compass, HeartHandshake, MapPin, ShieldCheck, Wallet } from "lucide-react";
import { MarketingShell } from "@/components/layout/marketing-shell";
import { AgencyLogo } from "@/components/layout/agency-logo";
import { TenantPackages } from "./tenant-packages";

export function TenantLanding({ context }: { context: PublicHostContext }) {
  const name = context.branding?.display_name ?? context.tenant?.name ?? "Your travel agency";
  return <MarketingShell tenant ctaLabel="Pilgrim sign in">
    <section className="relative overflow-hidden bg-[#153e35] text-[#fff8e9]">
      <div className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-14 sm:px-8 lg:grid-cols-[1.15fr_1fr] lg:py-20">
        <div className="relative z-10"><p className="mb-6 flex items-center gap-3 text-xs uppercase tracking-[.2em] text-[#dec899]"><span className="h-px w-8 bg-[#dec899]" />Travel with {name}</p><h1 className="max-w-2xl font-serif text-5xl leading-[1.1] sm:text-6xl lg:text-7xl">A sacred journey.<br /><span className="italic text-[#dec899]">A trusted companion.</span></h1><p className="mt-7 max-w-lg text-base leading-8 text-[#d0dfd7]">Discover Hajj, Umrah, and Ziyarah experiences with {name}. From preparing your family to arriving at your destination, we’re here for every step.</p><Link href="/packages" className="mt-8 inline-flex items-center gap-6 rounded-lg bg-[#e6d3ac] px-6 py-4 text-sm font-semibold text-[#153e35]">Explore our journeys <ArrowRight size={18} /></Link><div className="mt-10 flex flex-wrap gap-6 text-xs text-[#d0dfd7]"><span className="flex items-center gap-2"><HeartHandshake size={16} />Family bookings</span><span className="flex items-center gap-2"><Wallet size={16} />Flexible payments</span></div></div>
        <div className="relative mx-auto flex aspect-[4/5] w-full max-w-md flex-col justify-end overflow-hidden rounded-t-[220px] border border-[#dec899]/40 bg-[#214e42] px-6 pb-6">
          <div className="absolute inset-4 rounded-t-[210px] border border-[#dec899]/20" /><div className="absolute left-1/2 top-14 h-20 w-20 -translate-x-1/2 rounded-full bg-[#e6d3ac] shadow-[0_0_100px_#e6d3ac33]" />
          <svg viewBox="0 0 400 320" className="relative mt-28 w-full" role="img" aria-label="Architectural illustration inspired by the sacred mosque"><path d="M0 280h400v40H0z" fill="#bba884"/><path d="M10 280V174q30-70 60 0v106M330 280V174q30-70 60 0v106" fill="#728b70"/><path d="M86 280V108h24v172M290 280V108h24v172" fill="#e6d3ac"/><path d="M82 108l16-27 16 27M286 108l16-27 16 27" fill="#bba884"/><path d="M130 280V176q70-118 140 0v104" fill="#f5ebd3"/><path d="M123 176q77-145 154 0z" fill="#a5b394"/><path d="M180 280v-54q20-43 40 0v54" fill="#214e42"/><path d="M140 280v-42q12-29 24 0v42M236 280v-42q12-29 24 0v42" fill="#bba884"/><path d="M195 90h10v25h-10z" fill="#e6d3ac"/></svg>
          <p className="relative mt-2 text-center text-[10px] uppercase tracking-[.3em] text-[#dec899]">Faith in the journey. Care in every detail.</p>
        </div>
      </div>
    </section>
    <div className="border-b border-amber-800/10 bg-[#eee7d9] text-[#594d38]"><div className="mx-auto grid max-w-7xl gap-5 px-6 py-6 text-sm sm:grid-cols-3 sm:px-8">{[[Compass,"Journeys with purpose"],[ShieldCheck,"Your details, organized"],[HeartHandshake,"Support for your family"]].map(([Icon,label]) => { const I = Icon as typeof Compass; return <p key={String(label)} className="flex items-center justify-center gap-3"><I size={19} strokeWidth={1.5} />{String(label)}</p>; })}</div></div>
    <section id="journeys" className="mx-auto max-w-7xl px-6 py-16 sm:px-8"><div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs uppercase tracking-[.2em] text-amber-700 dark:text-amber-300">Find the journey for you</p><h2 className="mt-3 font-serif text-4xl">Our upcoming departures</h2></div><Link href="/packages" className="flex items-center gap-3 text-sm font-semibold">All packages <ArrowRight size={16} /></Link></div><TenantPackages /></section>
    <section id="features" className="mx-auto grid max-w-7xl gap-12 border-t border-amber-800/15 px-6 py-16 sm:px-8 md:grid-cols-2"><div><p className="text-xs uppercase tracking-[.2em] text-amber-700 dark:text-amber-300">With you, every step</p><h2 className="mt-4 max-w-md font-serif text-4xl leading-tight">Focus on what matters.<br /><span className="italic">We’ll help with the details.</span></h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-500">Choose your package, bring your family’s details together, and follow your booking from your personal pilgrim account.</p></div><div className="space-y-7">{[{icon:Compass,title:"Choose your experience",body:"Explore packages and select the travel tier that suits your plans."},{icon:CalendarDays,title:"Prepare together",body:"Keep your family’s pilgrim and passport information in one booking."},{icon:Wallet,title:"Pay your way",body:"Choose full payment or installments and follow your payments online."}].map(({icon:Icon,title,body},i)=><div key={title} className="flex gap-5"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-amber-700/25 text-amber-700 dark:text-amber-300"><Icon size={20} /></span><div><h3 className="font-semibold">0{i+1}. {title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p></div></div>)}</div></section>
    <section className="bg-[#eae1cf] px-6 py-14 text-center text-[#153e35]"><MapPin size={25} className="mx-auto mb-5" /><h2 className="font-serif text-4xl">Your next chapter starts with intention.</h2><Link href="/register" className="mt-7 inline-flex items-center gap-5 rounded-lg bg-[#153e35] px-6 py-3 text-sm text-white">Create your pilgrim account <ArrowRight size={16} /></Link></section>
    <footer className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6 px-6 py-10 sm:px-8"><AgencyLogo name={name} /><p className="text-xs text-slate-500">© {new Date().getFullYear()} {name} · Powered by Wufud</p><Link href="/login?next=/dashboard" className="text-xs text-slate-500">Agency staff sign in</Link></footer>
  </MarketingShell>;
}
